### PR TITLE
arb::util::variant fixes

### LINKED ISSUE #1093: Variant hash is broken
It's currently impossible to make an `unordered_map` with an `arb::util::variant` key because:
1. The `std::hash` overload is incorrect.
2. There is no `operator==` for `arb::util::variant`.

### PR DESCRIPTION
**Pull request by halfflat**
* Correct hash implementation.
* Add ==, != comparisons.

Fixes #1093

### CODE REVIEW

File: arbor/include/arbor/util/variant.hpp [hunk 1]
```diff
@@ -584,16 +614,16 @@ namespace std {
 // Unambitious hash:
 template <typename... T>
 struct hash<::arb::util::variant<T...>> {
-    std::size_t operator()(const ::arb::util::variant<T...>& v) {
+    std::size_t operator()(const ::arb::util::variant<T...>& v) const {
         return v.index() ^
-            visit([](const auto& a) { return std::hash<std::remove_cv_t<decltype(a)>>{}(a); }, v);
+            ::arb::util::visit([](const auto& a) { return std::hash<std::remove_cv_t<std::remove_reference_t<decltype(a)>>>{}(a); }, v);
```
Comment (bcumming) [inline arbor/include/arbor/util/variant.hpp:619]: Can you replace `remove_cv<remove_reference<>>` with `decay<>`?

Comment (halfflat) [reply arbor/include/arbor/util/variant.hpp:619]: It's not _quite_ the same (it doesn't turn arrays into pointers), so I think it matches the semantics more precisely.
