### PR TITLE
Fix reduce-by-key CUDA

### LINKED ISSUE #736: Hang with sequential use of `arb::gpu::reduce_by_key` on V100/CUDA 10.1
In at least one circumstance, calling `reduce_by_key` twice in succession within a kernel causes the kernel to hang. This behaviour is exhibited on a V100 with CUDA 10.1.

This is triggered in the GPU code with the stability correction.

* Try to isolate this in a unit test.
* Fix it.

### PR DESCRIPTION
**Pull request by bcumming**
Fix bug in CUDA `reduce_by_key` implementation on V100 or later GPUs.

The bug was not triggered for current use cases of the algorithm in Arbor, though it will be a problem when more than one reduction is to be performed in a single kernel invocation, which is required for accumulating both current and conductance values.

Fixes  #736.

### CODE REVIEW

File: arbor/backends/gpu/reduce_by_key.hpp [hunk 1]
```diff
@@ -96,74 +46,73 @@ float get_from_lane(float value, unsigned lane) {
...
 
-    while (width) {
-        unsigned source_lane = run.lane_id + width;
+    while (__any_sync(run.key_mask, shift)) {
+        const unsigned w = participate? shift: 0;
+        const unsigned source_lane = run.lane_id + w;
 
-        auto source_value = impl::get_from_lane(contribution, source_lane);
-        if (source_lane<rhs) {
+        T source_value = __shfl_sync(run.key_mask, contribution, source_lane);
```
Comment (halfflat) [inline arbor/backends/gpu/reduce_by_key.hpp]: It probably makes little difference, but I believe you could just use `__shfl_down_sync(..., w)` rather than compute `source_lane` explicitly.

File: arbor/backends/gpu/reduce_by_key.hpp [hunk 2]
```diff
@@ -11,80 +11,30 @@ namespace impl{
...
-#if __CUDACC_VER_MAJOR__ < 9
-    return __ballot(pred);
-#else
-    return __ballot_sync(mask_all, pred);
-#endif
-}
-
-// return the power of 2 that is less than or equal to i
+// Return the largest power of 2 that is less than i
+// Caveat: i must be non-zero.
```
Comment (halfflat) [inline arbor/backends/gpu/reduce_by_key.hpp]: Just regarding the comment: this returns the largest power of 2 no greater than i, right?

File: arbor/backends/gpu/reduce_by_key.hpp [hunk 3]
```diff
@@ -11,80 +11,30 @@ namespace impl{
...
-// TODO: CUDA 9 provides a double precision version of __shfl that
-// implements this hack. When we make CUDA 9 the minimum version, use
-// the CUDA implementation instead.
-
+// Return the first power of 2 that is larger than or equal to i
+// input i is in the closed interval [0, 2^31]
+// The result for i>2^31 is invalid, because it can't be stored in an
+// unsigned 32 bit integer.
+// This isn't a problem for the use case that we will use it for, because
+// it will be used for values in the range [0, threads_per_warp]
```
[the remark this answers is not in the document]
Comment (bcumming) [reply arbor/backends/gpu/reduce_by_key.hpp]: This function should be removed: it isn't needed.

File: modcc/printer/cudaprinter.cpp [hunk 4]
```diff
@@ -445,7 +449,7 @@ void emit_state_update_cu(std::ostream& out, Symbol* from,
         out << "arb::gpu::reduce_by_key(";
         is_minus && out << "-";
         out << from->name()
-            << ", params_." << d.data_var << ", " << index_i_name(d.index_var) << ");\n";
+            << ", params_." << d.data_var << ", " << index_i_name(d.index_var) << ", lane_mask_);\n";
```
[the remark this answers is not in the document]
Comment (bcumming) [reply modcc/printer/cudaprinter.cpp]: Yes, it is. Before doing the full conversion to calculating run-length outside `reduce_by_key`, more tests need to be added to the cuda printer to ensure that it is only called on `APIMethod`s that perform reductions.

I was not comfortable using the `__activemask` intrinsic to find the mask inside `reduce_by_key`, because the docs didn't convince me that there wouldn't be divergent threads, even directly after `__syncwarp`.

File: arbor/backends/gpu/reduce_by_key.hpp (hunk 1 above)
Comment (bcumming) [reply arbor/backends/gpu/reduce_by_key.hpp]: I think you are right.

File: arbor/backends/gpu/reduce_by_key.hpp (hunk 2 above)
Comment (bcumming) [reply arbor/backends/gpu/reduce_by_key.hpp]: Yes.
Due to other simplifications, this is no longer needed, and has been removed.

File: arbor/backends/gpu/reduce_by_key.hpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (bcumming) [reply arbor/backends/gpu/reduce_by_key.hpp]: Removed.

**Comment by bcumming** [comment]
Righteos, the algorithm has been simplified further, in a way that addresses all of the review comments (I think).

I also made modcc only generate a thread_mask for API Methods that write indexed variables. Not strictly neccesary, because I doubt that there are any performance overheads, but it makes for cleaner generated code.
