### PR TITLE
Change use of long double to double.

### LINKED ISSUE #1245: WSL: modcc unit test fails
Running the modcc unit tests on a Win10+WSL+Ubuntu 20.04 build has 1 test failing (all other tests are OK):
```
/home/user/arbor/test/unit-modcc/test_parser.cpp:663: Failure
The difference between eval(e.get()) and test_case.second is 7.4505805969238281e-09, which exceeds 1e-10, where
eval(e.get()) evaluates to -63281459.031249993,
test_case.second evaluates to -63281459.03125, and
1e-10 evaluates to 1e-10.
```

A bug has been filed in the WSL repo: https://github.com/microsoft/WSL/issues/830. `long double` is assumed to be 80 bit, but is 64 bit in WSL. 

Since as of today WSL still installs v1 rather than v2 by default, and this is a minor bug, we can change the test to a relative error, e.g.:
`EXPECT_TRUE(near_relative(eval(e.get()), test_case.second, 1e-10));`
We can instead not assume assumptions about `long double`, and change `eval()` accordingly.

### PR DESCRIPTION
**Pull request by brenthuisman**
Change from `long double` to `double` for storing floating point values in modcc.

WSL, and Windows generally, treats `long double` differently than Linux, which leads to inconsistencies in literal numeric values in code generated by modcc on the two platforms.

Fixes #1245

### CODE REVIEW

**Comment by halfflat** [comment]
We'd have to changed the uses of `long double` to `double` in `modcc` too.

**Comment by brenthuisman** [comment]
What about `long long`? I think those are OK, but please confirm :)

**Comment by halfflat** [comment]
I think we can consider changing `long long` to an explicit width type as something to consider in the scope of a different PR.

File: test/unit-modcc/test_parser.cpp [hunk 1]
```diff
@@ -656,10 +656,10 @@ TEST(Parser, parse_binop) {
         EXPECT_TRUE(check_parse(e, &Parser::parse_expression, test_case.first));
 
         // A loose tolerance of 1e-10 is required here because the eval()
-        // function uses long double for intermediate results (like constant
+        // function uses double for intermediate results (like constant
```
Comment (bcumming) [inline test/unit-modcc/test_parser.cpp:659]: This comment no longer makes sense.

**Review by bcumming — CHANGES_REQUESTED** [review]
Does this fix the test on WSL? I thought that the problem was that on WSL the `long double` was being treated as a `double`. If so, using `double` will still create the incorrect result.

How about we instead update the test to test for relative error, and not absolute error? I would like to keep the explicit, more accurate, compile time `long double` if possible.

**Comment by halfflat** [comment]
My issue with `long double` is that it bakes in a platform-dependent numerical interpretation in generated code, making reproducibility harder; it's not just that the specific numerical environment would need to be recreated (if this is indeed possible), but this has to be done on the platform that runs `modcc` _as well_ as on the execution platform.

It's not too stringent a requirement, I think, that we demand IEEE double precision semantics everywhere for correctness and reproducibility, but expecting `long double` behaviour to be the same everywhere is unreasonable.

**Comment by thorstenhater** [comment]
Question: What was the rationale for using long double in the first place?

**Comment by bcumming** [comment]
Rationale was that it was at least as accurate as double, likely more so. If we were going to do folding, might as well make it accurate. That was before I knew what I know now.

File: test/unit-modcc/test_parser.cpp (hunk 1 above)
Comment (brenthuisman) [reply test/unit-modcc/test_parser.cpp:659]: I'll remove it.

**Comment by brenthuisman** [comment]
The PR at present does make the unit-modcc test pass on Windows WSL.

**Review by bcumming — APPROVED** [review]
