### PR TITLE
Fix bug in `single_cell_model::probe`, fix probe frequency in examples

### LINKED ISSUE #1457: Empty plots are being generated in python examples
All the python examples using the `single_cell_model` are generating empty plots, specifically: 
* single_cell_detailed.py
* single_cell_model.py
* single_cell_nml.py
* single_cell_swc.py

### PR DESCRIPTION
**Pull request by noraabiakar**
* Fix the regular schedule generated in `single_cell_model::run`
* Adjust frequency of probes in python examples. 

Fixes #1457

### CODE REVIEW

File: python/single_cell_model.cpp [hunk 1]
```diff
@@ -194,7 +194,7 @@ class single_cell_model {
 
             traces_.push_back({"voltage", p.site, {}, {}});
 
-            auto sched = arb::regular_schedule(p.frequency);
+            auto sched = arb::regular_schedule(1.0/p.frequency);
```
Comment (brenthuisman) [inline python/single_cell_model.cpp:197]: Wow, can't believe it was not noticed before!

**Review by brenthuisman — APPROVED** [review]

File: python/example/single_cell_nml.py [hunk 2]
```diff
@@ -80,9 +80,9 @@
 m = arbor.single_cell_model(cell)
 
 # Attach voltage probes that sample at 50 kHz.
```
Comment (schmitts) [inline python/example/single_cell_nml.py:82]: 50 Hz vs. 50 kHz?
