### PR TITLE
Rethrow a more informative error if cell kind is not a `cell_kind`

### LINKED ISSUE #2138: Unclear error when `arbor.lif_cell` is mistaken for `arbor.cell_kind.lif`
```python
def get_cell_kind(self, gid):
  return arbor.lif_cell
```

I ran into this error:

```
    self.domain = arbor.partition_load_balance(recipe, context)
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

If it had not been the only change I made since the last run I'd have no idea what caused this error.

### PR DESCRIPTION
**Pull request by thorstenhater**
Fixes #2138.

### CODE REVIEW

File: python/recipe.hpp [hunk 1]
```diff
@@ -64,7 +64,12 @@ class py_recipe_trampoline: public py_recipe {
     }
 
     arb::cell_kind cell_kind(arb::cell_gid_type gid) const override {
-        PYBIND11_OVERRIDE_PURE(arb::cell_kind, py_recipe, cell_kind, gid);
+        try {
+            PYBIND11_OVERRIDE_PURE(arb::cell_kind, py_recipe, cell_kind, gid);
+        }
+        catch (const pybind11::cast_error& e) {
+            throw pybind11::type_error{"Couldn't convert return value of recipe.cell_kind(gid) to a cell_kind. Please check your recipe."};
```
Comment (Helveg) [inline python/recipe.hpp:71]: Is `cell_kind` a fully qualified unambiguous name of the expected return type? Maybe `to an arbor.cell_kind enum` or similar?

Comment (thorstenhater) [reply python/recipe.hpp:71]: Fully qualified within Arbor, yes. It should be enough of a hint, no?

**Review by Helveg — APPROVED** [review]

**Review by AdhocMan — APPROVED** [review]
lgtm
