### PR TITLE
Remove abuse of arg_v.

### LINKED ISSUE #1754: Pybind seems to interpret some `decor.paint` docstrs as default values
```
arbor.decor().paint()
```

```
TypeError: paint(): incompatible function arguments. The following argument types are supported:
    1. (self: arbor._arbor.decor, region: str, mechanism: arbor._arbor.density) -> None
    2. (self: arbor._arbor.decor, region: str = 'the region label or description.', Vm: Optional[float] = initial membrane voltage [mV]., cm: Optional[float] = membrane capacitance [F/m²]., rL: Optional[float] = axial resistivity [Ω·cm]., tempK: Optional[float] = temperature [Kelvin].) -> None
    3. (self: arbor._arbor.decor, region: str, *, ion_name: str, int_con: Optional[float] = Initial internal concentration [mM], ext_con: Optional[float] = Initial external concentration [mM], rev_pot: Optional[float] = Initial reversal potential [mV]) -> None
```

Some of them look intended, as they don't have quotes around them, but `region: str = 'the region label or description.'` feels extra wrong. I find these hints, even if they'd be intended pretty cluttering. The user will pretty much always already have most of the signature right, and has given a wrong type, is forgetting one, giving one too many. The arg names and types are much more important than the docstr and the docstr clutters the print.

### PR DESCRIPTION
**Pull request by thorstenhater**
Do not abuse `pybind::arg_v("name", T default, "description")` as `pybind::arg_v("name", "description")`.
Use descriptive names and `pybind::arg` instead.

Closes #1754

### CODE REVIEW

File: python/cells.cpp [hunk 1]
```diff
@@ -774,13 +774,15 @@ void register_cells(pybind11::module& m) {
             "The group of spike detectors has the label 'label', used for forming connections between cells.")
         .def("discretization",
             [](arb::decor& dec, const arb::cv_policy& p) { return dec.set_default(p); },
-            pybind11::arg_v("policy", "A cv_policy used to discretise the cell into compartments for simulation"))
+            pybind11::arg("policy"),
+             "A cv_policy used to discretise the cell into compartments for simulation")
```
Comment (Helveg) [inline python/cells.cpp:778]: These look like a different pattern, is this OK?

**Review by Helveg — COMMENTED** [review]
So, were all the argument descriptions dropped?

**Comment by thorstenhater** [comment]
`arg_v` is for use with default values, which these do not have. Consequently I shuffled the parameter description
into the function docstring where applicatble.

**Review by Helveg — APPROVED** [review]

**Review by brenthuisman — COMMENTED** [review]
Most of them just removed the docstring, right? Not that they were terribly useful.

**Comment by thorstenhater** [comment]
Yes, were redundant I removed them.

**Review by brenthuisman — APPROVED** [review]
