### PR TITLE
Isolate external catalogues from libarbor.a.

### LINKED ISSUE #1834: Hard-coded path to compiler spoils creating custom catalogue
`pip install arbor` (0.6) on Ubuntu 20.04.3 LTS fails to compile custom catalogue:

```
[ 60%] Building CXX object CMakeFiles/mycat-catalogue.dir/mycat_catalogue.cpp.o
Traceback (most recent call last):
  File "/home/sschmitt/HBP/FIPPA/FIPPAgithub/AdEx/venv/bin/arbor-build-catalogue", line 232, in <module>
    sp.run(make_cmd,  shell=True, check=True, stdout=out, stderr=err)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
 Error:

make[2]: /opt/rh/devtoolset-10/root/usr/bin/c++: Command not found
make[2]: *** [CMakeFiles/mycat-catalogue.dir/build.make:80: CMakeFiles/mycat-catalogue.dir/mycat_catalogue.cpp.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:79: CMakeFiles/mycat-catalogue.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

because the path to the compiler is hardcoded:

```
venv/bin/arbor-build-catalogue
110:set(CMAKE_CUDA_HOST_COMPILER /opt/rh/devtoolset-10/root/usr/bin/c++)

venv/lib64/cmake/arbor/arbor-config.cmake
51:set(ARB_CXX /opt/rh/devtoolset-10/root/usr/bin/c++)
```

Removing the prefix:

```
sed -i s#/opt/rh/devtoolset-10/root/usr/bin/##g venv/bin/arbor-build-catalogue venv/lib64/cmake/arbor/arbor-config.cmake
```

allows to compile the catalogue.

### PR DESCRIPTION
**Pull request by thorstenhater**
# Changes
- Bump ABI to v0.1.1
- Add `arb_mechanism` to bundle `type` and `interface`s
- Adjust `generate_catalogue` and `build_catalogue`
- Return `nullptr` for GPU interfaces if not enabled

# Open Questions
- How to tell CMake not to link against `libarbor.a` and only use headers?
- ~~How to get around `#ifdef ARB_GPU_ENABLED`~~ Update: just embrace it.

# Linked Issues
Fixes #1834

### CODE REVIEW

**Comment by bcumming** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

**Comment by thorstenhater** [comment]
Ran the full suite on JUWELS. No troubles. @bcumming

**Comment by thorstenhater** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

File: arbor/mechcat.cpp [hunk 1]
```diff
@@ -608,7 +608,32 @@ const mechanism_catalogue& load_catalogue(const std::string& fn) {
...
+    mechanism_catalogue result;
+    for(int ix = 0; ix < count; ++ix) {
+        auto type = mechs[ix].type();
+        auto name = std::string{type.name};
+        if (name == "") {
+            throw bad_catalogue_error{util::pprintf("Empty name for mechanism in '{}'", fn)};
+        }
+        auto icpu = mechs[ix].i_cpu();
+        auto igpu = mechs[ix].i_gpu();
+        if (!icpu && !igpu) {
```
Comment (bcumming) [inline arbor/mechcat.cpp:625]: This is enforcing a requirement that a mechanism must have _at least one_ implementation?

File: doc/internals/mechanism_abi.rst [hunk 2]
```diff
@@ -444,16 +444,32 @@ interface layer <simd>` for more information.
...
 
-Mechanisms interface with Arbor by providing three functions, one
-returning the metadata portion, and one for each implemented backend (currently
-two). The latter may return a NULL pointer, indicating that this backend is not
-supported. The naming scheme is shown in the example below
+Mechanisms interface with Arbor by providing a single function, returning
+a structure
+
+.. c:struct:: arb_mechanism
+
```
Comment (bcumming) [inline doc/internals/mechanism_abi.rst:451]: Add the requirement that at least one of `i_cpu` or `i_gpu` has to be defined.

File: test/unit/test_mechcat.cpp [hunk 3]
```diff
@@ -282,10 +282,8 @@ TEST(mechcat, names) {
 TEST(mechcat, loading) {
     EXPECT_THROW(load_catalogue(LIBDIR "/does-not-exist-catalogue.so"), file_not_found_error);
     EXPECT_THROW(load_catalogue(LIBDIR "/libarbor.a"), bad_catalogue_error);
-    const mechanism_catalogue* cat = nullptr;
-    EXPECT_NO_THROW(cat = &load_catalogue(LIBDIR "/dummy-catalogue.so"));
-    ASSERT_NE(cat, nullptr);
-    EXPECT_EQ(std::vector<std::string>{"dummy"}, cat->mechanism_names());
+    const mechanism_catalogue cat = load_catalogue(LIBDIR "/dummy-catalogue.so");
```
Comment (bcumming) [inline test/unit/test_mechcat.cpp:285]: FYI, I don't think these tests are run by default on our CI.
When building with meson, the dynamic libraries have the extension `.dylib`, not `.so`, which causes this to break.
Not something to fix here (a bit out of scope), but something that will bite us on the behind at some point.

**Review by bcumming — CHANGES_REQUESTED** [review]
Looks good. There is a tiny suggested update to the docs.

**Comment by bcumming** [comment]
bors try

File: test/unit/test_mechcat.cpp (hunk 3 above)
Comment (thorstenhater) [reply test/unit/test_mechcat.cpp:285]: In the CMake build they are renamed to avoid this exactl problem. Is that an option in Meson?

File: arbor/mechcat.cpp (hunk 1 above)
Comment (thorstenhater) [reply arbor/mechcat.cpp:625]: Yes ... it's probably not strictly needed, but the sooner we reported these kind of issues...

**Comment by thorstenhater** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

**Comment by thorstenhater** [comment]
bors try

**Comment by brenthuisman** [comment]
bors try

**Comment by thorstenhater** [comment]
Seems stuck on Arm SVE ... no reason. @bcumming can you rescue us?

**Comment by brenthuisman** [comment]
Let's give @bcumming till the end of the week, and merge if no further feedback was obtained. ARM is no showstopper ATM.

**Comment by thorstenhater** [comment]
@bcumming :wave:

File: test/unit/test_mechcat.cpp (hunk 3 above)
Comment (eli-schwartz) [reply test/unit/test_mechcat.cpp:292]: In Meson this is the `name_suffix: 'so'` kwarg.

That being said, I would think for OS integration it might feel a bit more natural to use something like `LIBDIR "/dummy-catalogue." LIB_EXT` and pass that as a per-platform define?

**Comment by brenthuisman** [comment]
bors try

**Comment by brenthuisman** [comment]
Since AULT failing is the only test not passing, as per agreement past team meeting, I'll force merge.
