### PR TITLE
Fix cv_policy parse and write in ACC

### LINKED ISSUE #1660: GUI can't load CV policy
Loading an `acc` in the GUI containing

```
    (decor 
      (default 
        (membrane-potential -65.000000))
      (default 
        (axial-resistivity 90.000000))
      (default 
        (membrane-capacitance 0.010000))
      (default 
        (max-extent 1 
          (all)
          0))
```

fails with

```
[2021-09-14 10:37:36.087] [debug] Reading ACC from /home/sschmitt/HBP/arbor/python/example/foo.acc
[2021-09-14 10:37:36.096] [debug] Failed to load ACC: No matches for found for max-extent with 3 arguments.
There are 0 potential candiates. at :28:10
```

image

### PR DESCRIPTION
**Pull request by noraabiakar**
- Allow CV policies to be parsed and written as a `defaultable` in an ACC decor description. 
- The format used is `(default (cv-policy (_cv-policy-sexpr_)))`. 
- Add unit tests. 
- Fix strange white-space formatting.

Fixes #1660

### CODE REVIEW

File: arborio/cableio.cpp [hunk 1]
```diff
@@ -536,17 +540,19 @@ parse_hopefully<std::any> eval(const s_expr& e, const eval_map& map, const eval_
...
         }
 
+        // Or it could be a cv-policy expression
+        if (auto p = parse_cv_policy_expression(e)) return p.value();
+
         // Unable to find a match: try to return a helpful error message.
         const auto nc = std::distance(matches.first, matches.second);
         std::string msg = "No matches for found for "+name+" with "+std::to_string(args->size())+" arguments.\n"
-                          "There are "+std::to_string(nc)+" potential candiates"+(nc?":":".");
+                          "There are "+std::to_string(nc)+" potential candidates"+(nc?":":".");
```
Comment (thorstenhater) [inline arborio/cableio.cpp:555]: Thanks.

File: arborio/cableio.cpp [hunk 2]
```diff
@@ -558,34 +564,36 @@ parse_hopefully<std::any> eval(const s_expr& e, const eval_map& map, const eval_
 
 eval_map named_evals{
     {"membrane-potential", make_call<double>(make_init_membrane_potential,
-                               "'membrane-potential' with 1 argument (val:real)")},
+        "'membrane-potential' with 1 argument (val:real)")},
```
Comment (thorstenhater) [inline arborio/cableio.cpp:567]: Hard to follow here, there's a lot of whitespace changes, but is there any functional diff here?

**Review by thorstenhater — APPROVED** [review]
Looks good, although the amount of whitespace diff makes it hard to follow.

File: arborio/cableio.cpp (hunk 2 above)
Comment (thorstenhater) [reply arborio/cableio.cpp:567]: 👍
